const FAQSection = () => {
  const faqs = [
    {
      question: "What is the purpose of Design AI?",
      answer:
        "Design AI is an intelligent tool that simplifies the design process by generating creative and personalized solutions for your interiors.",
    },
    {
      question: "How accurate are the designs generated by AI?",
      answer:
        "Our AI delivers highly precise and realistic interior design concepts, which can be further refined with expert assistance.",
    },
    {
      question: "What kind of data do I need to provide to use Design AI?",
      answer:
        "You need to share basic details like space dimensions, style preferences, and functional requirements.",
    },
    {
      question: "Is human intervention required after AI generates the designs?",
      answer:
        "While AI provides a great starting point, our team ensures the final output meets your specific requirements.",
    },
    {
      question: "How does Design AI save time and cost?",
      answer:
        "By automating initial design processes, it reduces the time spent on revisions and eliminates unnecessary expenses.",
    },
  ];

  return (
    <div className="p-6 bg-green-50 bg-[#f3fafa] mx-4 md:mx-36 rounded-se-3xl my-10">
      <h2 className="text-3xl font-bold text-green-700 text-center mb-6">
        Frequently Asked Questions
      </h2>
      <div className="space-y-4 max-w-4xl mx-auto">
        {faqs.map((faq, index) => (
          <div
            key={index}
            tabIndex={0}
            className="collapse collapse-arrow border border-green-300 bg-green-100 rounded-lg"
          >
            <div className="collapse-title text-lg font-medium text-green-800">
              {faq.question}
            </div>
            <div className="collapse-content text-gray-700">
              <p>{faq.answer}</p>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default FAQSection;
